
//DECLARE ALL PERMITED ACTIONS

export const GET_RATES_REQUEST = 'GET_RATES_REQUEST';
export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS';
export const GET_RATES_ERROR   = 'GET_RATES_ERROR';
export const RESET_RATES       = 'RESET_RATES';

export const CREATE_CURRENCIES = 'CREATE_CURRENCIES';

export const GET_INFO_REQUEST  = 'GET_INFO_REQUEST';
export const GET_INFO_SUCCESS  = 'GET_INFO_SUCCESS';
export const GET_INFO_ERROR    = 'GET_INFO_ERROR';

export const CONVERTOR_SELECT_SOURCE      = 'CONVERTOR_SELECT_SOURCE';
export const CONVERTOR_SELECT_DESTINATION = 'CONVERTOR_SELECT_DESTINATION';
export const CONVERTOR_INPUT_SOURCE       = 'CONVERTOR_INPUT_SOURCE';
export const CONVERTOR_INPUT_DESTINATION  = 'CONVERTOR_INPUT_DESTINATION';
